language: go
go:
  - 1.9.x
  - 1.10.x
  - 1.11.x

branches:
  only:
  - master

install: make bootstrap
after_success:
  # only report coverage for go-version 1.11
  - if [[ $TRAVIS_GO_VERSION =~ ^1\.11 ]] ; then bash <(curl -s https://codecov.io/bash); fi
